controller_list:
  - name: fake_robotleg_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
initial:  # Define initial robot poses.
#  - group: robotleg
#    pose: home

  []