robotleg:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Trajectory Controller
  robotleg_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    
    constraints:
      goal_time: 10
      stopped_velocity_tolerance: 0.05
      joint1:
        trajectory: 0.1
        goal: 0.1
      joint2:
        trajectory: 0.1
        goal: 0.1
      joint3:
        trajectory: 0.1
        goal: 0.1
      joint4:
        trajectory: 0.1
        goal: 0.1
    
    gains:
      joint1: {p: 200, i: 20, d: 5}
      joint2: {p: 200, i: 20, d: 5}
      joint3: {p: 200, i: 20, d: 5}
      joint4: {p: 50, i: 20, d: 5}

    state_publish_rate: 50
    action_monitor_rate: 50
    stop_trajectory_duration: 0.5